### PR TITLE
closes #448 - deleted link in the footer, view left untouched

### LINKED ISSUE #448: The news site needs to be disabled
As for now there are no news to be posted on the website, the whole sub-site http://volontuloapp.org/pages/site-news needs to be disabled.

### PR DESCRIPTION
**Pull request by KrzysztofMadejski**
**Story / Bug id:** https://github.com/stxnext-csr/volontulo/issues/CC-5790
**Reference person:** @yourgithubname
**Description:**

Description of your changes.

**New imports / dependencies:**
- `package`

**Unit Tests:**
- `apps/volontulo/tests/views/test_auth.py`

**What tests do I need to run to validate this change:**

Description of testing workflow and potential affected places.

### CODE REVIEW

**Comment by magul** [comment]
The plan is, that if we are going to remove link, we need also to remove view and urls.

**Comment by KrzysztofMadejski** [comment]
I've cleaned the view, it's ready for merge

**Comment by tomaszwozniak** [comment]
looks good

**Comment by magul** [comment]
:+1: - merging.

**Pull request merged**
