### PR TITLE
Error after an attempt to create an offer 

### PR DESCRIPTION
**Pull request by kzuraw**
**Story / Bug id:** https://github.com/stxnext-csr/volontulo/issues/461
**Reference person:** @krzysztofzuraw
**Description:** Error after an attempt to create an offer 
**New imports / dependencies:**-
**Unit Tests:**
- `apps/volontulo/tests/views/test_offers.py`

**What tests do I need to run to validate this change:**-

### CODE REVIEW

**Comment by tomaszwozniak** [comment]
$ pep8 --exclude='apps/volontulo/migrations/*,node_modules,.ropeproject' .
./apps/volontulo/models.py:172:5: E303 too many blank lines (2)
./apps/volontulo/lib/email.py:62:73: W291 trailing whitespace
./apps/volontulo/tests/views/test_offers.py:219:1: W293 blank line contains whitespace
./apps/volontulo/tests/views/test_offers.py:221:5: E303 too many blank lines (2)
./apps/volontulo/views/offers.py:102:32: W291 trailing whitespace

**Comment by nbbn** [comment]
@krzysztofzuraw  Do you try to fix #417 by "Right now user can pick date"? I work on that (#417) issue.

**Comment by kzuraw** [comment]
@nbbn Ok no problem I reverted my last commit. Go on!

**Comment by tomaszwozniak** [comment]
:+1:

**Comment by msobas** [comment]
:+1:  merge it :)

**Pull request merged**
